# Generates the mod's data overrides from the game's own files, so the repo
# never ships (copyrighted) game content. Run by build.bat.
#
#  - <GameDir>\vrmod_overrides\Scripts\MovieBarn.lua: the level movies off
#    (they play black on some PCs and can't be skipped).
#  - With -NoCamGrabs: <GameDir>\vrmod_overrides\Scripts\Level_N\TriggerInstances.lua
#    with every SnapToCamTrigger's camDuration set to 0: the trigger still fires
#    (slow-down, events) but the camera doesn't fly to its placed shot - in VR
#    you can just look. (Setting camSnappiness/lookAtBlend to 0 instead made the
#    camera go haywire.) With -NoCamShake as well, camera shake
#    (useCameraRumble) is turned off too. Without -NoCamGrabs, those files are
#    removed again.
#
# The mod serves files in vrmod_overrides in place of the game's (see
# src/fileredirect.cpp). Delete a file there to restore the original.
# Usage: .\make_overrides.ps1 [-GameDir C:\...\Flower_GOG] [-NoCamGrabs] [-NoCamShake]
param([string]$GameDir = "$env:USERPROFILE\Desktop\Flower_GOG", [switch]$NoCamGrabs, [switch]$NoCamShake)

$scripts = Join-Path $GameDir 'Data\Scripts'

# Level movies off.
$src = Join-Path $scripts 'MovieBarn.lua'
if (Test-Path $src) {
    $text = [IO.File]::ReadAllText($src)
    $text = [regex]::Replace($text, '(start|finish)\s*=\s*"[^"]*"', '$1 = false')
    $dir = Join-Path $GameDir 'vrmod_overrides\Scripts'
    New-Item -ItemType Directory -Force $dir | Out-Null
    $header = "-- VRMod override: level movies off. Generated by tools/make_overrides.ps1`r`n" +
              "-- from the game's file; delete to restore the movies.`r`n"
    [IO.File]::WriteAllText((Join-Path $dir 'MovieBarn.lua'), $header + $text)
    "MovieBarn.lua: level movies off"
} else {
    Write-Warning "$src not found; movie override not generated"
}

# Camera grabs (SnapToCamTrigger).
$outRoot = Join-Path $GameDir 'vrmod_overrides\Scripts'
Get-ChildItem $scripts -Directory -Filter 'Level_*' | ForEach-Object {
    $out = Join-Path (Join-Path $outRoot $_.Name) 'TriggerInstances.lua'
    if (-not $NoCamGrabs) {
        if (Test-Path $out) { Remove-Item $out; "$($_.Name): camera grabs restored" }
        return
    }
    $src = Join-Path $_.FullName 'TriggerInstances.lua'
    if (-not (Test-Path $src)) { return }
    $text = [IO.File]::ReadAllText($src)
    # Split into per-object blocks; only touch SnapToCamTrigger blocks.
    $blocks = [regex]::Split($text, '(?=\{\s*ObjectName\s*=)')
    $changed = 0
    for ($i = 0; $i -lt $blocks.Count; $i++) {
        if ($blocks[$i] -match 'TriggerType\s*=\s*"SnapToCamTrigger"') {
            $b = [regex]::Replace($blocks[$i], 'camDuration\s*=\s*[-0-9.eE]+', 'camDuration = 0')
            if ($b -ne $blocks[$i]) { $changed++ }
            $blocks[$i] = $b
        }
        # Camera shake (the controller rumble stays).
        if ($NoCamShake) { $blocks[$i] = [regex]::Replace($blocks[$i], 'useCameraRumble\s*=\s*true', 'useCameraRumble = false') }
    }
    $new = $blocks -join ''
    if ($new -ne $text) {
        New-Item -ItemType Directory -Force (Split-Path $out) | Out-Null
        $header = "-- VRMod override: SnapToCamTrigger camera moves off (camDuration = 0, $changed triggers)$(if ($NoCamShake) { ', no camera shake' }).`r`n" +
                  "-- Generated by tools/make_overrides.ps1 -NoCamGrabs from the game's file; delete to restore.`r`n"
        [IO.File]::WriteAllText($out, $header + $new)
        "$($_.Name): $changed camera grab(s) off$(if ($NoCamShake) { ', camera shake off' })"
    }
}
