# Generates the mod's data overrides from the game's own files, so the repo
# never ships (copyrighted) game content. Run by build.bat.
#
#  - <GameDir>\vrmod_overrides\Scripts\MovieBarn.lua: the level movies off
#    (they play black on some PCs and can't be skipped).
#  - With -Experimental: <GameDir>\vrmod_overrides_experimental\Scripts\Level_N\
#    TriggerInstances.lua with every SnapToCamTrigger neutralized
#    (camSnappiness = 0, lookAtBlend = 0): the triggers still fire but no longer
#    swing the camera to a placed overhead shot. The mod does not read that
#    folder; copy files into vrmod_overrides to try them. EXPERIMENTAL: made the
#    camera go haywire in a test.
#
# The mod serves files in vrmod_overrides in place of the game's (see
# src/fileredirect.cpp). Delete a file there to restore the original.
# Usage: .\make_overrides.ps1 [-GameDir C:\...\Flower_GOG] [-Experimental]
param([string]$GameDir = "$env:USERPROFILE\Desktop\Flower_GOG", [switch]$Experimental)

$scripts = Join-Path $GameDir 'Data\Scripts'

# Level movies off.
$src = Join-Path $scripts 'MovieBarn.lua'
if (Test-Path $src) {
    $text = [IO.File]::ReadAllText($src)
    $text = [regex]::Replace($text, '(start|finish)\s*=\s*"[^"]*"', '$1 = false')
    $dir = Join-Path $GameDir 'vrmod_overrides\Scripts'
    New-Item -ItemType Directory -Force $dir | Out-Null
    $header = "-- VRMod override: level movies off. Generated by tools/make_overrides.ps1`r`n" +
              "-- from the game's file; delete to restore the movies.`r`n"
    [IO.File]::WriteAllText((Join-Path $dir 'MovieBarn.lua'), $header + $text)
    "MovieBarn.lua: level movies off"
} else {
    Write-Warning "$src not found; movie override not generated"
}

if (-not $Experimental) { return }

$outRoot = Join-Path $GameDir 'vrmod_overrides_experimental\Scripts'
Get-ChildItem $scripts -Directory -Filter 'Level_*' | ForEach-Object {
    $src = Join-Path $_.FullName 'TriggerInstances.lua'
    if (-not (Test-Path $src)) { return }
    $text = [IO.File]::ReadAllText($src)
    # Split into per-object blocks; only touch SnapToCamTrigger blocks.
    $blocks = [regex]::Split($text, '(?=\{\s*ObjectName\s*=)')
    $changed = 0
    for ($i = 0; $i -lt $blocks.Count; $i++) {
        if ($blocks[$i] -match 'TriggerType\s*=\s*"SnapToCamTrigger"') {
            $b = [regex]::Replace($blocks[$i], 'camSnappiness\s*=\s*[-0-9.eE]+', 'camSnappiness = 0')
            $b = [regex]::Replace($b, 'lookAtBlend\s*=\s*[-0-9.eE]+', 'lookAtBlend = 0')
            if ($b -ne $blocks[$i]) { $changed++ }
            $blocks[$i] = $b
        }
    }
    if ($changed -gt 0) {
        $dir = Join-Path $outRoot $_.Name
        New-Item -ItemType Directory -Force $dir | Out-Null
        $header = "-- VRMod override: SnapToCamTrigger camera moves neutralized ($changed triggers).`r`n" +
                  "-- Generated by tools/make_overrides.ps1 from the game's file; delete to restore.`r`n"
        [IO.File]::WriteAllText((Join-Path $dir 'TriggerInstances.lua'), $header + ($blocks -join ''))
        "$($_.Name): $changed SnapToCamTrigger(s) neutralized"
    }
}
