# Generates overrides/Scripts/Level_N/TriggerInstances.lua from the game's own
# files with every SnapToCamTrigger neutralized (camSnappiness = 0,
# lookAtBlend = 0): the triggers still fire (events, slow-down, duration) but
# no longer swing the camera to a placed overhead shot - jarring in VR.
# Usage: .\make_overrides.ps1 [-GameDir C:\...\Flower_GOG]
param([string]$GameDir = "$env:USERPROFILE\Desktop\Flower_GOG")

# EXPERIMENTAL (made the camera go haywire in a test): written to overrides_experimental,
# which build.bat does not deploy.
$outRoot = Join-Path $PSScriptRoot '..\overrides_experimental\Scripts'
Get-ChildItem (Join-Path $GameDir 'Data\Scripts') -Directory -Filter 'Level_*' | ForEach-Object {
    $src = Join-Path $_.FullName 'TriggerInstances.lua'
    if (-not (Test-Path $src)) { return }
    $text = [IO.File]::ReadAllText($src)
    # Split into per-object blocks; only touch SnapToCamTrigger blocks.
    $blocks = [regex]::Split($text, '(?=\{\s*ObjectName\s*=)')
    $changed = 0
    for ($i = 0; $i -lt $blocks.Count; $i++) {
        if ($blocks[$i] -match 'TriggerType\s*=\s*"SnapToCamTrigger"') {
            $b = [regex]::Replace($blocks[$i], 'camSnappiness\s*=\s*[-0-9.eE]+', 'camSnappiness = 0')
            $b = [regex]::Replace($b, 'lookAtBlend\s*=\s*[-0-9.eE]+', 'lookAtBlend = 0')
            if ($b -ne $blocks[$i]) { $changed++ }
            $blocks[$i] = $b
        }
    }
    if ($changed -gt 0) {
        $dir = Join-Path $outRoot $_.Name
        New-Item -ItemType Directory -Force $dir | Out-Null
        $header = "-- VRMod override: SnapToCamTrigger camera moves neutralized ($changed triggers).`r`n" +
                  "-- Generated by tools/make_overrides.ps1 from the game's file; delete to restore.`r`n"
        [IO.File]::WriteAllText((Join-Path $dir 'TriggerInstances.lua'), $header + ($blocks -join ''))
        "$($_.Name): $changed SnapToCamTrigger(s) neutralized"
    }
}
